import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/legal/privacy-policy")({
  component: PrivacyPolicyPage,
  head: () => ({
    meta: [
      { title: "Privacy Policy | Rapulana Attorneys" },
      { name: "description", content: "How Rapulana Attorneys collects, uses, and protects personal information under POPIA." },
      { property: "og:title", content: "Privacy Policy | Rapulana Attorneys" },
      { property: "og:description", content: "How Rapulana Attorneys collects, uses, and protects personal information under POPIA." },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
});

function PrivacyPolicyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <main className="flex-1">
        <section className="border-b border-border bg-secondary/30">
          <div className="container-prose py-12">
            <p className="eyebrow text-gold">Legal</p>
            <h1 className="mt-2 text-4xl font-semibold tracking-tight md:text-5xl">Privacy Policy</h1>
            <p className="mt-4 max-w-2xl text-muted-foreground">
              How we collect, use, and safeguard personal information in line with the Protection of Personal
              Information Act. Last updated 22 June 2026.
            </p>
          </div>
        </section>
        <section className="container-prose py-12">
          <article className="prose prose-neutral max-w-none prose-headings:font-semibold prose-headings:tracking-tight prose-h2:mt-10 prose-h2:text-2xl prose-h3:text-xl prose-p:leading-relaxed">
            <p className="rounded-lg border border-border bg-secondary/40 p-4 text-sm">
              This Privacy Policy is subject to the Terms and Conditions of Rapulana Attorneys. By continuing to
              use the Rapulana Attorneys' website, you agree to the terms and conditions set out in this Privacy
              Policy. By submitting information via any format to Rapulana Attorneys, you consent to the
              collection, collation, processing and storing of such information and the use and disclosure of such
              information in accordance with this Privacy Policy. We recommend that you read this Privacy Policy
              together with our Terms and Conditions prior to submitting information to this website.
            </p>

            <h2>1. Introduction</h2>
            <p>
              This is the Privacy Policy of Rapulana Attorneys (hereinafter referred to as 'us', 'we' or 'our' as
              required by the context). Rapulana Attorneys shall be referred to as interchangeable and will apply
              to the Rapulana Attorneys website. In this Privacy Policy we list our policies regarding the
              collection, use, and disclosure of Personal Information or data when you use our service and the
              choices you have associated with that data. We use your data to provide and improve our service.
              By using the service, you agree to the collection and use of information in accordance with this
              Privacy Policy.
            </p>
            <p>
              The provisions as set out in this Privacy Policy are in conjunction with the provisions as set out in
              the Terms and Conditions of our website.
            </p>

            <h2>2. Definitions</h2>
            <p>The following words, expressions and abbreviations shall have the meaning hereinafter assigned to them:</p>
            <ul>
              <li>
                <strong>'Service'</strong> means the service(s) and/or products provided on our Rapulana Attorneys
                website as advertised by email, electronic communications or other marketing campaigns under
                the same name operated by this company;
              </li>
              <li>
                <strong>'Personal Information'</strong> means data about a living individual (you) who can be
                identified from that data (or from those and other information either in our possession or likely to
                come into our possession), such as your name, contact details, your company details and service
                history. It may also contain other information as reasonably applicable from time to time;
              </li>
              <li>
                <strong>'Data or Content'</strong> means data collected automatically either generated by the use
                of service and providing certain information or from the service infrastructure itself which includes
                Personal Information;
              </li>
              <li>
                <strong>'Data Controller'</strong> means the natural or legal person who (either alone or jointly or
                in common with other persons) determines the purposes for which and manner in which any
                personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a
                Data Controller of your Personal Information, Content or Data;
              </li>
              <li>
                <strong>'Data Processors or Service Providers'</strong> means any natural or legal person who
                processes the data on behalf of the data controller. We may use the services of various Service
                Providers in order to process your data more effectively; and
              </li>
              <li>
                <strong>'Data Subject or user'</strong> means any living individual who is using our service and is
                the subject of Personal Information.
              </li>
            </ul>

            <h2>3. Consent</h2>
            <h3>3.1 How does Rapulana Attorneys get your consent?</h3>
            <p>
              We obtain your consent when you provide us with personal information on our website or by way of
              your voluntary submission thereof on any electronic communication platforms. Further, we obtain
              your consent if we ask for your Personal Information for a secondary reason (such an example of
              marketing). We will either ask you directly for your expressed consent, or provide you with an
              opportunity to say no.
            </p>
            <h3>3.2 How do I withdraw my consent?</h3>
            <p>
              If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for
              the continued collection, use or disclosure of your information, at any time, by contacting us at
              rethabile@rapulana.co.za.
            </p>

            <h2>4. Age of Consent</h2>
            <p>
              By using the Rapulana Attorneys website, you represent that you are at least the age of majority in
              your province of residence and you have given us your consent to allow any of your minor
              dependents to use this website.
            </p>

            <h2>5. Information Collection</h2>
            <p>
              When you provide us with your personal information as set out in clause 3.1 above, we collect the
              personal information you give us to provide our service to the user.
            </p>
            <h3>Personal Information, Data and Content</h3>
            <p>
              By using the Rapulana Attorneys website you represent that you are at least the age of majority in
              your province of residence, or that you are the age of majority in your state or province of residence
              and you have given us your consent to allow any of your minor dependents to use this website.
            </p>
            <p>
              While using our Service, we may ask you to provide us with certain personally identifiable
              information that can be used to contact or identify you. Personally identifiable information may
              include, but is not limited to:
            </p>
            <ul>
              <li>
                Any identifying number, symbol, e-mail address, physical address, telephone number, location
                information, online identifier or other particular assignment to you;
              </li>
              <li>
                Your name if it appears with your other personal information or if your name itself would reveal
                information about you.
              </li>
            </ul>
            <p>
              We may use your Data to contact you regarding your profile, research, contact you with our
              newsletter, announcement emailer or promotional materials and other information that may be of
              interest to you or us. You may opt out of receiving any, or all, of these communications from us by
              following the unsubscribe process or instructions provided in any email we send or by contacting
              us at rethabile@rapulana.co.za.
            </p>
            <h3>Data</h3>
            <p>
              You may be asked or be required to provide limited personal information to enable us to provide
              certain services to you. We may store this information manually or electronically. We will only use
              it for purposes for which it was provided, if you have consented to it. Information provided will be
              kept for as long as necessary to fulfil that purpose.
            </p>
            <p>
              We may also collect personal information about your employment and any aggregate information
              which shall be submitted to our Data Controller. Further included will be statistical data about our
              users' actions and patterns which do not identify individuals and allows us to ensure that content
              from our website is presented in the most effective manner for you and your business.
            </p>

            <h2>6. Use of Information and Data Collected</h2>
            <p>We use the collected data for various purposes not limited to the below:</p>
            <ul>
              <li>To deliver the services you have asked for. In other words, to provide and maintain our service;</li>
              <li>Research;</li>
              <li>To notify you about changes to our service;</li>
              <li>To allow you to participate in interactive features of our service when you choose to do so;</li>
              <li>To provide client support;</li>
              <li>To gather analysis or valuable information so that we can improve our service;</li>
              <li>To monitor the usage of our service;</li>
              <li>To detect, prevent and address technical issues;</li>
              <li>
                To provide you with news, special offers and general information about other goods, services and
                events which we offer that are similar to those that you already used or enquired about unless you
                have opted not to receive such information;
              </li>
              <li>
                If you subscribe for data, news, announcements, alerts or any such information to be emailed to
                you, we will hold your details on our database until such time as you chose to unsubscribe from
                this service. You may do this at any stage by selecting the appropriate option and notification;
              </li>
              <li>
                Personal information will not be sold to third parties, or provided to direct marketing companies
                or other such organizations without your permission. We may disclose your personal information
                to third parties if we are under a duty to disclose or share such.
              </li>
            </ul>

            <h2>7. Retention of Personal Information, Content and Data</h2>
            <p>
              We will retain your personal information, content and data only for as long as is necessary for the
              purposes set out in this Privacy Policy. We will retain and use your data to the extent necessary to
              provide our service and for research to comply with legal obligations.
            </p>

            <h2>8. Transfer of Personal Information, Content and Data</h2>
            <p>
              Your data may be transferred to, and maintained on, computers located outside of your province or
              country or other governmental jurisdiction where the data protection laws may differ than those
              from your jurisdiction.
            </p>
            <p>
              Please note that we may transfer data, to the locations of our third-party service providers' servers
              and process it required or necessary. Your consent to this Privacy Policy followed by your
              submission of such information represents your agreement to that transfer.
            </p>
            <p>
              We will take reasonable steps to ensure that your data is treated securely and in accordance with
              this Privacy Policy and no transfer of data will take place to an organization or a country unless
              there are adequate controls in place including the security of your data and other personal
              information.
            </p>

            <h2>9. Disclosure of Data</h2>
            <p>For purposes of research, we may disclose your data to relevant institutions for research purposes.</p>
            <p>
              Legal requirements may require us to disclose your data, however, this is done in good faith and
              with the belief that such action is necessary to:
            </p>
            <ul>
              <li>Comply with a legal obligation;</li>
              <li>Protect and defend the rights or property of the proprietor of this business networking forum;</li>
              <li>Prevent or investigate possible wrongdoing in connection with the service;</li>
              <li>Protect the personal safety of users of the service or the public; and</li>
              <li>Protect against legal liability.</li>
            </ul>

            <h2>10. Security of Data</h2>
            <p>
              To protect your personal information, we take reasonable precautions and follow industry best
              practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or
              destroyed.
            </p>

            <h2>11. Third Party Services</h2>
            <p>
              In general, the third-party providers used by us will only collect, use and disclose your information
              to the extent necessary to allow them to perform the services they provide to us.
            </p>
            <p>
              In particular, remember that certain providers may be located in or have facilities that are located
              in a different jurisdiction to that of either you or us. Thus, if you elect to proceed with a transaction
              that involved the services of a third-party service provider, then your information may become
              subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.
            </p>
            <p>
              Once you leave our website or are redirected to a third-party, you are no longer governed by this
              Privacy Policy or our website Terms and Conditions.
            </p>

            <h2>12. Changes to this Privacy Policy</h2>
            <p>
              We reserve the right to modify this Privacy Policy at any time, so please review it frequently.
              Changes and clarification will take effect immediately upon posting on the appropriate
              communication platforms of Rapulana Attorneys. If we make material changes to this policy, we will
              notify you here that it has been updated, so that you are aware of what information we collect, how
              we use it, and under what circumstances, if any, we use and/or disclose it.
            </p>

            <h2>13. Applicable Laws</h2>
            <p>
              This Privacy Policy is governed by the laws of the Republic of South Africa, and you consent to the
              jurisdiction of the South African courts in respect of any dispute which may arise out of or in
              connection with the formation, interpretation, substance or application of this Privacy Policy.
            </p>

            <h2>14. Questions and Contact Information</h2>
            <p>
              If you would like to access, amend, correct or delete any personal information we have about you,
              register a complaint, or simply want more information, contact us at{" "}
              <a href="mailto:info@rapulana.co.za">info@rapulana.co.za</a>.
            </p>
          </article>
        </section>
      </main>
    </div>
  );
}
